<div class="text-center" style="max-height:300px;overflow-y:scroll">
<?php foreach ($data as $vData) {
    $username = $vData['username'];
    $name = $vData['name'];
    $email = $vData['email'];
    $icon = $vData['icon'];
    $initials = $vData['initials'];
    $refNO = $vData['ref_no'];
    $school = (array)$vData['school'];
?>
    <form class="text-center add-member-matched" style="display:inline-block;">
        <input type="hidden" name="username" value="<?=H($username)?>" />
        <input type="hidden" name="name" value="<?=H($name)?>" />
        <input type="hidden" name="email" value="<?=H($email)?>" />
        <div class="add-member-icon">
            <div class="add-member-icon-image">
                <?php if ($icon && parse_url($icon)['scheme']!='initials') { ?>
                <img src="<?=H($icon)?>" />
                <?php } else { ?>
                <div class="add-member-icon-text">
                    <?php if ($initials) { ?>
                        <span><?=H($initials)?></span>
                    <?php } else { ?>
                        <span class="fa fa-question"></span>
                    <?php } ?>
                </div>
                <?php } ?>
            </div>
            <div class="add-member-icon-title"><?=H(T('姓名: :name', [':name'=>$name?:T('未知用户')]))?></div>
            <div class="add-member-icon-title"><?=H(T('学工号: :refno', [':refno'=>$refNO?:'--']))?></div>
            <div class="add-member-icon-title"><?=H(T('学院: :school', [':school'=>$school['name']?:'--']))?></div>
        </div>
        <div style="padding-bottom:5px;"><input type="button" class="add-member-confirm btn btn-primary" value="<?=H(T('确认添加'))?>" /></div>
    </form>
<?php }?>
</div>
