<div class="modal fade">
    <div class="modal-dialog add-member-modal">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><?=H(T('添加成员'))?></h4>
            </div>
            <div class="modal-body">
                <form class="form" method="POST" action="">
                    <div class="form-group add-member-username">
                        <?php
                        $vTitle = \Gini\Config::get('gapper.gateway-add-member-title');
                        if ($vTitle=='${GATEWAY_ADD_MEMBER_TITLE}') {
                            $vTitle = '输入成员一卡通帐号';
                        }
                        ?>
                        <label class="text-muted"><?=H($vTitle)?></label>
                        <input type="text" class="form-control" name="username" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

